---
title: 9 to 5 programming
email: sdemichowicz at google
description: 'I just work 9 to 5. I also work beyond this hours, but then I am just
  not paid. '
baseurl: https://9to5programming.com/
url: https://9to5programming.com/
twitter_username: Demichowicz
github_username: demee
theme: minima
plugins:
- jekyll-menus
