---
title: 9 to 5 programming
email: sdemichowicz at google
description: 'I just work 9 to 5. I also work beyond these hours, but then I am just
  not paid. '
baseurl: 
url: 
twitter_username: Demichowicz
github_username: demee
theme: minima
plugins:
- jekyll-menus
